return {
  "romus204/tree-sitter-manager.nvim",
  lazy = false,
  config = function()
    require("tree-sitter-manager").setup({
      ensure_installed = {
        "luadoc",
        "printf",
        "vim",
        "vimdoc",
        "markdown",
        "latex",
        "markdown_inline",
        "query",
        "ini",
        "udev",
        "ssh_config",
        "tmux",
        "kitty",
        "diff",
        "git_config",
        "gitcommit",
        "git_rebase",
        "gitignore",
        "gitattributes",
        "regex",
        "rasi",
        "sql",
        "lua",
        "bash",
        "java",
        "rust",
        "python",
        "c",
        "asm",
        "cpp",
        "hyprlang",
        "go",
        "gomod",
        "gowork",
        "gosum",
        "php",
        "blade",
        "yaml",
        "toml",
        "xml",
        "json",
        "qmljs",
        "html",
        "css",
        "javascript",
        "typescript",
        "tsx",
        "astro",
        "svelte",
        "prisma",
      },
      -- Avoid re-installing Neovim core bundled parsers
      assume_installed = {
        "c",
        "lua",
        "markdown",
        "markdown_inline",
        "query",
        "vim",
        "vimdoc",
      },
      noauto_install = {
        "c",
        "lua",
        "markdown",
        "markdown_inline",
        "query",
        "vim",
        "vimdoc",
      },

      highlight = true,
      border = "single",
      auto_install = true,
      nerdfont = true,
    })
  end,
}
